// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtCPmLubAMVk6xYRySFO9Te6ddrzFYg4U',
    appId: '1:295041187460:web:875201d788c7e5cca30cd1',
    messagingSenderId: '295041187460',
    projectId: 'mynotes-freecodecamp-tutorial',
    authDomain: 'mynotes-freecodecamp-tutorial.firebaseapp.com',
    storageBucket: 'mynotes-freecodecamp-tutorial.appspot.com',
    measurementId: 'G-XHJS1SJY6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB24FmltMy48jyGTD98FHiKQjorB4aM1ks',
    appId: '1:295041187460:android:45936a7651d2c54ba30cd1',
    messagingSenderId: '295041187460',
    projectId: 'mynotes-freecodecamp-tutorial',
    storageBucket: 'mynotes-freecodecamp-tutorial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm5oTZKXYh1WersP7EJgDim-DiOIXu-S4',
    appId: '1:295041187460:ios:1390767b677e34bda30cd1',
    messagingSenderId: '295041187460',
    projectId: 'mynotes-freecodecamp-tutorial',
    storageBucket: 'mynotes-freecodecamp-tutorial.appspot.com',
    iosClientId: '295041187460-u90ri5oua4htb7d6bu9amkl40e5gnjlm.apps.googleusercontent.com',
    iosBundleId: 'com.learningdart.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm5oTZKXYh1WersP7EJgDim-DiOIXu-S4',
    appId: '1:295041187460:ios:1390767b677e34bda30cd1',
    messagingSenderId: '295041187460',
    projectId: 'mynotes-freecodecamp-tutorial',
    storageBucket: 'mynotes-freecodecamp-tutorial.appspot.com',
    iosClientId: '295041187460-u90ri5oua4htb7d6bu9amkl40e5gnjlm.apps.googleusercontent.com',
    iosBundleId: 'com.learningdart.mynotes',
  );
}
